add drop_table function

diff --git a/db1/check b/db1/check
--- a/db1/check
+++ b/db1/check
@@ -238,3 +238,40 @@ insert_into_table() {
 #     cd ..
 #     mainmenu
 # }
+##############################################################################################
+drop_table() {
+
+    DBName="$1"
+    ##tables=$(ls Database/$DBName | grep -v "_metaData")
+    ##
+    Tables2=($(ls "Database/$DBName" | grep -v "_metaData"))
+    optionsTables3=()
+    for ((l = 0; l < ${#Tables2[@]}; l++)); do
+        optionsTables3+=("${Tables2[$l]}")
+    done
+
+    TableName3=$(zenity --width=300 --height=300 --list --title="Select Tables in ${DBName}" --column="Tables" "${optionsTables3[@]}" \
+        --text="Select Table in ${DBName}")
+    ##
+    ##TableName=$(zenity --width=300 --height=300 --entry --title="Drop Table" --text="Enter the name of the table:")
+    if [ $? -eq 0 ]; then
+        if [ -n "$TableName3" ]; then
+            for file in $TableName3; do
+                if [ "$TableName3" == "$file" ]; then
+                    rm Database/$DBName/$TableName3
+                    rm "Database/$DBName/${TableName3}_metaData"
+                    zenity --width=300 --height=150 --info --title="Table Dropped" --text="Table $TableName3 dropped successfully in $DBName database."
+                    break
+                else
+                    zenity --width=300 --height=150 --error --title="Table Not Found" --text="Table $TableName3 does not exist."
+                    break
+                fi
+            done
+        else
+            zenity --width=300 --height=150 --error --title="Error" --text="You did not select table.❌"
+        fi
+    else
+        menu
+    fi
+}
+
